### ISSUE TITLE
Change composer installation location

### ISSUE THREAD

**Issue by kevinruscoe** [devgeniem/acf-codifier#117]
Now that ACF supports installing via composer (yay), when installing it you can specify a path to where the plugin is installed to. This is great because if you require it from a composer file within your theme, you can change the path to correctly install in wp-content/plugins

It seems with this plugin, you can't change the path. So if i install this plugin within a theme, it always puts the plugin inside wp-content/themes/my-theme/wp-content/mu-plugin

Is it possible to change this installation path?

**Comment by HPiirainen** [comment]
Sorry for the (very) late response, but you can use Composer's `installer-paths` logic to install a package wherever you like. It does not have to be taken into account within the context of this plugin.

See https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md.

F. ex.

```
"installer-paths": {
    "whatever/you/like/{$name}/": [
        "devgeniem/acf-codifier"
    ]
}
```
