### ISSUE TITLE
Error with Advanced Custom Fields Pro < 6.3.0 

### ISSUE THREAD

**Issue by ronilaukkarinen** [devgeniem/acf-codifier#129]
> Fatal error: Declaration of Geniem\ACF\Fields\Multitaxonomy::get_term_title($term, $field, $post_id = 0) must be compatible with acf_field_taxonomy::get_term_title($term, $field, $post_id = 0, $unescape = false) in .../mu-plugins/acf-codifier/src/Fields/Multitaxonomy.php on line 141

This error occurs in all versions after [6.3.0](https://www.advancedcustomfields.com/changelog/).

acf-codifier version in use: 1.41.1.

**Comment by HPiirainen** [comment]
Fixed via #128 (kudos @jaakkolehtonen) in release [1.41.2](https://github.com/devgeniem/acf-codifier/releases/tag/1.41.2).
