### ISSUE TITLE
ACF Pro 6.3.10 compatibility

### ISSUE THREAD

**Issue by msaari** [devgeniem/acf-codifier#130]
Latest version of Codifier causes a fatal error with ACF Pro 6.3.10. The `render_field_select()` function in /Fields/Multitaxonomy.php needs a second parameter `$nonce`.

**Comment by HPiirainen** [comment]
@msaari - thanks, I'll try to fix this ASAP.

**Comment by HPiirainen** [comment]
@msaari - published version 1.41.3, the issue should be fixed there.
