### ISSUE TITLE
Fix label not being hidden after cloning a field

### ISSUE THREAD

**Issue by Nomafin** [devgeniem/acf-codifier#14]
Label doesn't become hidden if the field has been cloned.

Also, if a label of a group field has been hidden, all the labels from its subfields get hidden as well.

**Comment by villesiltala** [comment]
The latter can be fixed by modifying the CSS in Codifer.php:46:
```
echo 'div.acf-field.acf-field-' . $key . " > div.acf-label > label { display: none; }\n";
```
