### ISSUE TITLE
Warning while adding a field into a group

### ISSUE THREAD

**Issue by natanaelsinisalo** [devgeniem/acf-codifier#52]
I'm getting a PHP Warning while trying to add a new field into a group.

The code i'm using:

```php
<?php

namespace Geniem\ACF;

$field_group = new Group( 'Test Group' );

$rule_group = new RuleGroup();
$rule_group->add_rule( 'post_type', '==', 'page' );
$field_group->add_rule_group( $rule_group );

$textarea = new Field\Textarea( 'Textarea' );
$field_group->add_field( $textarea );

$field_group->register();
```

And the error i'm getting in the edit post view just before the field title:

`Warning: trim() expects parameter 1 to be string, array given in /xxx/wp-content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php on line 665`

Versions:

ACF PRO 5.7.3
ACF Codifier 1.3.0
WordPress 4.9.8
PHP 7.2.5

The WordPress is just a fresh install with only ACF PRO and ACF Codifier installed.

Any ideas on why this is happening?

Please let me know if you need any further information about my dev environment.

**Comment by Nomafin** [comment]
Have you tried updating to a more recent version of ACF Codifier? If I remember right, that bug was fixed somewhere along the way after 1.3.0.

**Comment by natanaelsinisalo** [comment]
Oh i see now. Just blindly followed the installation instructions and used the release link in the documentation which is still pointing to 1.3.*. It might be a good idea to point the link in the documentation to the releases page instead of a single release zip to avoid issues like this.

Thanks for the quick reply!

**Comment by Nomafin** [comment]
Thanks for pointing this out. Corrected the link in Readme to point to the latest release now.
